name: OilRigs
main: oilrigs.OilRigs
version: 1.0
api-version: 1.13
author: oceanichelicopter
commands:
    or:
        description: Base oilrigs command. Use get to get an item or reload to reload the config
        usage: /or
    oilReload:
        description: Realods the Config for Oilrigs
        usage: /oilreload

        
permissions:
    oilrigs.Commands:
        description: perms to do oilrigs commands
        default: op